### ISSUE TITLE
繁中及英文介面 背景圖都是簡中文字

### ISSUE THREAD

**Issue by lukechang0815** [isuncloud/windows_client#4]
server ver: mgt_1.0.0.18mgt_1.0.0.18 win7
client: setup20150215 win7

step
開始進入login畫面
result
出現簡中背景

step 
右鍵點選系統欄叫出我的雲盤功能後點選 關於
result:
出現簡中背景

![default](https://cloud.githubusercontent.com/assets/11328863/6684846/f17fffca-cccf-11e4-82f0-85834f54683f.png)
![default](https://cloud.githubusercontent.com/assets/11328863/6684847/f1860726-cccf-11e4-9eb0-69851a8634a5.png)
![default](https://cloud.githubusercontent.com/assets/11328863/6684849/f1887a06-cccf-11e4-8623-e5d7bdb6f41c.png)
![default](https://cloud.githubusercontent.com/assets/11328863/6684848/f18636b0-cccf-11e4-996d-b1e864297803.png)

**Comment by neojason** [comment]
先以繁中為主

**Comment by lukechang0815** [comment]
RD 已经修改

**Comment by lukechang0815** [comment]
20150515 圖片背景中文字刪除
